### ISSUE TITLE
Problem with updating swephR on CRAN

### ISSUE THREAD

**Issue by rstub** [prajwalkpatil/VedicDateTime#11]
Hi,
I am maintaining the swephR package that you are using. I have to update the package, because it is using some C constructs that are no longer accepted by CRAN. Fortunately, the current version of the underlying C library fixes these. Unfortunately, this changes the computation for some things slightly. And this causes some tests in your package to fail. As a consequence, I cannot update swephR.

I see at least two possibilities:
* You could reformulate the tests such that you are not testing for the explicit values and instead just test the general structure.
* You could reformulate the tests such the expected result would depend on the version of swephR being used.

Do you have any preferences? Or do you have other ideas?

If you are interested, I could provide a PR for one of these approaches. The problem is, that a new release for VedicDateTime would be needed quite soon so that swephR can also be released within the time frame set by CRAN. 

Thanks for considering!

**Comment by prajwalkpatil** [comment]
Hi,

Thanks for opening this issue. I don't think we can write general tests for the functions present in this package. I am finding your second option to be more suitable for this issue. Calculations and the values might change slightly based on the changes you make to the SwephR package.  The tests can be changed as per the recent version of SwephR. 

I will be really grateful if you can make a PR fixing the tests. I hope there is no change in the syntax of the SwephR function calls.

I will definitely make a CRAN submission of the recent version of the package with updated tests as soon as new version of SwephR is released. Please do let me know when that happens.

Thanks again!

**Comment by rstub** [comment]
Ok, I have created #12. Thanks for considering!

However, we might have to think about a longer term solution. These kind of (small) changes are introduced with (almost) every update of SWE, and I am already updating the tests in swephR as a consequence. I am not sure it makes sense for you having to make a release of VedicDateTime with updated tests whenever I want to make a new swephR release.

**Comment by rstub** [comment]
Thanks for merging my PR. Do you know when you will be able to upload the version to CRAN?

**Comment by rstub** [comment]
@prajwalkpatil, @neerajdhanraj,
As you might have seen in the email I got from CRAN: The deadline for getting a fixed version of swephR unto CRAN has been extended by one week until 2023-05-12. Will you be able to upload a new version of VedicDateTime before that? Do you need any help with that?

**Comment by prajwalkpatil** [comment]
Thanks for the concern.

@neerajdhanraj is the maintainer of this package on CRAN. Submission should be made via his email address so, I can't help. 
I too have mailed him regarding this. We can only make a submission when he replies.
