### ISSUE TITLE
Multiple ritu names are returned by get_ritu_name when adhika masa flag is set by the  masa function

### ISSUE THREAD

**Issue by sanivella** [prajwalkpatil/VedicDateTime#20]
Multiple ritu names are returned by **get_ritu_name** when adhika masa flag is set by the  **masa** function

When it is Adhika masa, flag 1 is set, **get_ritu_name** returns multiple ritu names as array

e.g. For 18 July 2023

```
> masa(gregorian_to_jd(18,07,2023),  c(16.99, 81.79, +5.5))
[1] 5 1
> get_ritu_name(masa(gregorian_to_jd(18,07,2023),  c(16.99, 81.79, +5.5)))
[1] "Varsha"  "Vasanta"

```
where as for a non adhika masa, only single ritu name is returned 

e.g. For 18 August 2023

```
> masa(gregorian_to_jd(18,08,2023),  c(16.99, 81.79, +5.5))
[1] 5 0
> get_ritu_name(masa(gregorian_to_jd(18,08,2023),  c(16.99, 81.79, +5.5)))
[1] "Varsha"
```

**Comment by prajwalkpatil** [comment]
We truly appreciate the time and effort you put into bringing this matter to our attention.

Your feedback is incredibly valuable to us and helps us make our package better. By pointing out this issue, you've helped us identify areas for improvement and ensure the package works well for everyone.

Thank you.
